server:
    port: 8087
spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/springboot?serverTimezone=Asia/Seoul
        username: root
        password: mysql
        driver-class-name: com.mysql.cj.jdbc.Driver

    freemarker:
        cache: false
    thymeleaf:
        cache: false

mybatis:
    type-aliases-package: com.example.springbootmybatis.entity
    mapper-locations: mapper/**/*.xml