server:
    port: 8087
spring:
    data:
        mongodb:
            uri: mongodb://127.0.0.1:27017/sixthsense
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/springboot?serverTimezone=Asia/Seoul
        username: root
        password: mysql
        driver-class-name: com.mysql.cj.jdbc.Driver
    mail:
        host: smtp.gmail.com
        port: 587
        username: seolroh@gmail.com
        password: 2726115a@
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

#    spring.mail.host=smtp.gmail.com
#    spring.mail.port=587
#    spring.mail.username=발신인메일@gmail.com   ex) hodoo.tistory@gmail.com
#    spring.mail.password=발신인메일의 비밀번호   ex) password
#    spring.mail.properties.mail.smtp.auth=true
#    spring.mail.properties.mail.smtp.starttls.enable=true

    freemarker:
        cache: false
    thymeleaf:
        cache: false

mybatis:
    type-aliases-package: com.companyd.hompage.seoul.entity
    mapper-locations: mapper/*.xml